apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices-kubernetes-demo-order
spec:
  selector:
    matchLabels:
      app: microservices-kubernetes-demo-order
  replicas: 1
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: microservices-kubernetes-demo-order
        tier: frontend
    spec:
      containers:
        - name: microservices-kubernetes-demo-order
          image: gcr.io/eshaul-work/microservices-kubernetes-demo-order
          ports:
            - containerPort: 8080
              name: http-server
            - containerPort: 5005
              name: debug
