apiVersion: v1
kind: Service
metadata:
  name: microservices-kubernetes-demo-apache
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: microservices-kubernetes-demo-apache
    tier: frontend