apiVersion: v1
kind: Service
metadata:
  name: microservices-kubernetes-demo-catalog
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: microservices-kubernetes-demo-catalog
    tier: frontend