apiVersion: v1
kind: Service
metadata:
  name: microservices-kubernetes-demo-customer
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: microservices-kubernetes-demo-customer
    tier: frontend